### ISSUE TITLE
self-hosted bitbucket?

### ISSUE THREAD

**Issue by humblewebdev** [nishio-dens/bitbucket-pullrequest-builder-plugin#100]
Will this ever be made to work with self-hosted bitbucket servers?

**Comment by tomislacker** [comment]
@humblewebdev the APIs are a bit different (if I recall correctly) but for what it's worth, I'm putting together a similar solution using webhooks as [StashNotifier](https://wiki.jenkins-ci.org/display/JENKINS/StashNotifier+Plugin) with my self-hosted BitBucket system. I just confirmed the notifier works.
