### ISSUE TITLE
Cannot get credentials to work anymore (git plugin >= 3.0)?

### ISSUE THREAD

**Issue by brianrepko** [nishio-dens/bitbucket-pullrequest-builder-plugin#101]
We can use the username and password fields to get this plugin working again but post plugin updates cannot get the credentials to work. There isn't really anything in this code or the plain-text credentials plugin code that points to a change but the git plugin update to 3.0 might be a cause of this. It would be nice to have the wiki tags and dependencies for credentials specified (like the Github Pull Request Builder plugin has).

Issue is also at https://issues.jenkins-ci.org/browse/JENKINS-34773 with more detail.

**Comment by brianrepko** [comment]
PlainCredentials plugin did change (Sep 23, 2016) 

https://github.com/jenkinsci/plain-credentials-plugin/compare/plain-credentials-1.2...plain-credentials-1.3

which changes some code around encryption of File based credentials but I think that is just code refactoring and not actual encryption changes.

**Comment by ip1981** [comment]
Use ssh-agent.

**Comment by CodeMonk** [comment]
@brianrepko Is this still an issue?

**Comment by brianrepko** [comment]
@CodeMonk omg... I don't think so anymore - you should just close this
