### ISSUE TITLE
Incorrect environment variables

### ISSUE THREAD

**Issue by Siecje** [nishio-dens/bitbucket-pullrequest-builder-plugin#114]
When running a build from a fork the environment variables

`MERCURIAL_REPOSITORY_URL` and `MERCURIAL_REVISION` were set to the latest commit in the destination repo for the pull request.

I would expect them to be the values from the pull request source

**Comment by CodeMonk** [comment]
@Siecje Could you paste your entire environment from the build? (Please scrub out any IP first)

**Comment by Siecje** [comment]
I was trying to run a build from a Bitbucket fork. The source wasn't the fork. As I understand running a build from a fork is not supported by this plugin.

**Comment by Siecje** [comment]
There was a feature request here https://github.com/nishio-dens/bitbucket-pullrequest-builder-plugin/issues/23.

I would like this feature. Currently we are not able to run CI on pull requests. We only run CI once the PR is merged :(.

**Comment by CodeMonk** [comment]
Ok -- I've reopened that issue, and I'm going to close this one.
