### ISSUE TITLE
Integrate with Bitbucket's "Pull Request POST" hook

### ISSUE THREAD

**Issue by bmannix** [nishio-dens/bitbucket-pullrequest-builder-plugin#12]
Bitbucket provides a hook that fires when a pull request is created or when configurable events occur.  It would be very nice if this plugin could integrate with bitbucket's hook (even if it was just a tickle that would kick off the existing polling) so the cron schedule would become unnecessary, builds would fire immediately, and it would cut down on network traffic.

https://confluence.atlassian.com/display/BITBUCKET/Pull+Request+POST+hook+management

**Comment by akhyrul** [comment]
+1

**Comment by Epilgrim** [comment]
+1

**Comment by DoDoENT** [comment]
+1

**Comment by tgeens** [comment]
That link 404's now ?

Could this be a duplicate of #60 ?

**Comment by bmannix** [comment]
#60 - is a generic request for push notification based builds (one of which could be the pull request builder).  But yeah, I'd say that #60 is essentially a duplicate of this (much older) ticket.  

The new link is: https://confluence.atlassian.com/bitbucket/manage-webhooks-735643732.html

**Comment by itsSaad** [comment]
2 years later. We still need this. 👍

**Comment by lifeofguenter** [comment]
+1

**Comment by ip1981** [comment]
+1 :)
