### ISSUE TITLE
It should force to disapprove when options "Approve if build success" is checked and build is failed.

### ISSUE THREAD

**Issue by chrisLeeTW** [nishio-dens/bitbucket-pullrequest-builder-plugin#120]
Hi,

As topic described.

We got two jeknis build with same Merged Request in the almost same time sometimes.

In this situation.  

If one build job is success first, and second build job is failed in the end.

We will see that jenkins ci user is approved, but build is failed XD

So it should force to disapprove when options "Approve if build success" is checked and build is failed.

BR
Chris.

**Comment by CodeMonk** [comment]
There is a lot of debate about this, since a decline on bitbucket is pretty brutal.

Closing this as an enhancement (There are multiple PRs vying for this.)
