### ISSUE TITLE
Pipeline project with Jenkinsfile from scm

### ISSUE THREAD

**Issue by mattjohnson** [nishio-dens/bitbucket-pullrequest-builder-plugin#130]
I got the plugin working by including the config in the Jenkinsfile however I had to load the Jenkinsfile directly into Jenkins instead of allowing it to be pulled from source control. When it is pulled from source control and the Pipeline job is configured to checkout the Jenkinsfile from the repo it fails to resolve the variables ${sourceBranch} ${repositoryOwner} and ${repositoryName}.

I'd like to be able use the Jenkinsfile from the repo. Let me know how I can help.

**Comment by CodeMonk** [comment]
This should work now. -- please confirm.

And, by "now" I mean in the fix I just merged from #177
