### ISSUE TITLE
feature request: Multi-BitBucket Repo PULL request builder

### ISSUE THREAD

**Issue by DuaneEllis-TI** [nishio-dens/bitbucket-pullrequest-builder-plugin#133]
In my environment - we have several repos that need to be monitored.

Example:
     REPO (A) = application
     REPO (B) = library (1)
     REPO (C) = library (2) - etc 

Today - the pull request monitor only supports a *SINGLE* repo.
My need is to monitor multiple repos in an "OR" fashion.

If a pull request is opened on any of the (N) repos - I need to trigger the build.
I cannot use pipeline - for other reasons, I cannot use the GIT recursive checkout

(See below for some background/detail)

Thanks.

**BACKGROUND**

We sometimes have a pull request that crosses multiple repos.

for example - I add a feature to a library, and to the application - i need to test both together.

In my case - Both pull requests generally have the same "name"
For example:   feature/JIRA-1234-foobar-feature

But I would think in the *NORMAL* case this would not always be the case.
Some one else might have two different project names, and two different set of JIRA tags.

For example:  feature/LIB-1234-foobar-feature
And  feature APP-54321-foobar feature

**Comment by CodeMonk** [comment]
So, PRs would exist in multiple repos - would they all trigger a common build? or just one of them would trigger the build for all of them?

I'm thinking if you have the PR trigger the library build, in your example, the post build action could be to then build the application.

Would that work for your scenario?

**Comment by CodeMonk** [comment]
This should be fixed in #177
