### ISSUE TITLE
"approve if build success" not working

### ISSUE THREAD

**Issue by fcanela** [nishio-dens/bitbucket-pullrequest-builder-plugin#136]
Aside from credentials and marking "Approve if build success" checkbox. Is there any other requisite? I have succeeding builds but PR are not shown as approved at Bitbucket.

The only error that could be applicable is the following which appears in Jenkins process (not build):

```
com.squareup.okhttp.internal.Platform$JdkWithJettyBootPlatform getSelectedProtocol
INFO: NPN/ALPN callback dropped: SPDY and HTTP/2 are disabled. Is npn-boot or alpn-boot on the boot class path?
```

Jenkins is running from the official docker image.

I am pasting the available logs in case you can deduce something useful from them.

Job log:
```
Started by BitBucket push by redacted
Started by BitBucket push by redacted
Started by BitBucket push by redacted
Started by BitBucket push by redacted
Building in workspace /var/jenkins_home/workspace/test-pr
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Done
Cloning the remote Git repository
Cloning repository https://redacted@bitbucket.org/redacted/jenkins-test.git
 > git init /var/jenkins_home/workspace/test-pr # timeout=10
Fetching upstream changes from https://redacted@bitbucket.org/redacted/jenkins-test.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials 
 > git fetch --tags --progress https://redacted@bitbucket.org/redacted/jenkins-test.git +refs/heads/*:refs/remotes/origin/*
 > git config remote.origin.url https://redacted@bitbucket.org/redacted/jenkins-test.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://redacted@bitbucket.org/redacted/jenkins-test.git # timeout=10
Fetching upstream changes from https://redacted@bitbucket.org/redacted/jenkins-test.git
using GIT_ASKPASS to set credentials 
 > git fetch --tags --progress https://redacted@bitbucket.org/redacted/jenkins-test.git +refs/heads/*:refs/remotes/origin/*
Seen branch in repository origin/master
Seen branch in repository origin/test
Seen branch in repository origin/test-2
Seen 3 remote branches
 > git tag -l # timeout=10
Merging Revision d69a457a0a70a9fddb2bfb78b29b9f4d8f40cae0 (origin/test-2) to origin/master, UserMergeOptions{mergeRemote='origin', mergeTarget='master', mergeStrategy='default', fastForwardMode='--ff'}
 > git rev-parse origin/master^{commit} # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f origin/master
 > git merge --ff d69a457a0a70a9fddb2bfb78b29b9f4d8f40cae0 # timeout=10
 > git rev-parse HEAD^{commit} # timeout=10
Seen branch in repository origin/master
Seen branch in repository origin/test
Seen branch in repository origin/test-2
Seen 3 remote branches
 > git tag -l # timeout=10
Checking out Revision d69a457a0a70a9fddb2bfb78b29b9f4d8f40cae0 (origin/test-2, origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f d69a457a0a70a9fddb2bfb78b29b9f4d8f40cae0
Commit message: "Pushing changes"
 > git rev-list 6f724979bb917ef96e73adbbfd37df0c4a60d9fd # timeout=10
 > git rev-list 6f724979bb917ef96e73adbbfd37df0c4a60d9fd # timeout=10
Run condition [Always] enabling prebuild for step [BuilderChain]
Run condition [Always] enabling perform for step [BuilderChain]
[test-pr] $ /bin/sh -xe /tmp/jenkins6519909153636570314.sh
+ echo Simulating job. This should succeed
Simulating job. This should succeed
Bitbucket Approve: https://api.bitbucket.org/2.0/repositories/redacted/jenkins-test/commit/d69a457a0a70a9fddb2bfb78b29b9f4d8f40cae0/approve
[WS-CLEANUP] Deleting project workspace...[WS-CLEANUP] done
Finished: SUCCESS

```

Note that the succeeding Bitbucket Approve is from another plugin that approves the commit, not the PR.

The related Jenkins stdout:

```
INFO: Processing new Webhooks payload
Oct 23, 2017 12:39:55 PM com.cloudbees.jenkins.plugins.BitbucketPayloadProcessor processWebhookPayload
INFO: Received commit hook notification for [[redacted]]
Oct 23, 2017 12:39:55 PM com.cloudbees.jenkins.plugins.BitbucketJobProbe triggerMatchingJobs
INFO: Triggering BitBucket job test-pr
Oct 23, 2017 12:39:55 PM com.cloudbees.jenkins.plugins.BitBucketTrigger$1 run
INFO: SCM changes detected in test-pr. Triggering  #45
Oct 23, 2017 12:39:57 PM com.cloudbees.jenkins.plugins.BitBucketTrigger$1 run
INFO: SCM changes detected in test-pr. Triggering  #45
Oct 23, 2017 12:40:14 PM hudson.model.Run execute
INFO: test-pr #45 main build action completed: SUCCESS
Oct 23, 2017 12:40:14 PM com.squareup.okhttp.internal.Platform$JdkWithJettyBootPlatform getSelectedProtocol
INFO: NPN/ALPN callback dropped: SPDY and HTTP/2 are disabled. Is npn-boot or alpn-boot on the boot class path?
```

**Comment by blakelloyd-coderus** [comment]
I may be having the same issue, builds are succeeding but the PR is not being approved. What's strange is I have other projects that do publish correctly, the only difference with this repo is it's using pipelines instead of the norm. Are you also using Pipelines?

**Comment by ip1981** [comment]
I doubt this feature even makes sense.

1. You can configure BB to block merging if a build is not successful.
2. Having approval from a robot is weird :)

**Comment by blakelloyd-coderus** [comment]
Forgot to add, it's not reporting the build as successful on Bitbucket, only on Jenkins itself, but yeah I see where you're coming from

**Comment by CodeMonk** [comment]
@fcanela I think this has been fixed -- can you confirm?

**Comment by celicoo** [comment]
It's not, I'm having this issue.

**Comment by CodeMonk** [comment]
@celicoo Can you provide logs, please, so we can make sure it's not a different issue, since this one was supposed to have been fixed?

**Comment by CodeMonk** [comment]
This is fixed in mainline and will be in the next release. Issue was treating the comment response of 201 as an error.

**Comment by CodeMonk** [comment]
@ysabri : I just pushed a release a few minutes ago - Hopefully it worked.

Most jobs getting triggered multiple times comes from the plugin failing to add the comment when it does a build triggered by the phrase.

Or, maybe, you have a very simple phrase that many people are putting into comments -- the phrase can appear ANYWHERE inside of the comment.

**Comment by ysabri** [comment]
Still same issue.

I might be doing something wrong or missing something. Do I need any hooks on bitbucket side? Cause I have added none.

I have removed the phrase, put one that doesn't exist in the PR, and put one that does. Nothing changed the behavior.

**Comment by CodeMonk** [comment]
With 1.4.28?

**Comment by CodeMonk** [comment]
@ysabri Well, that's unfortunate, but, at least now we have a bit of activity here, so let's see if we can fix it!

First, we're going to need more information, and, this particular ticket is closed. So, if it's not too much trouble, would you mind doing the following:

Please create a new issue here to track the behavior your are seeing. Please include logs and screenshots of your configuration. If possible, limit your logs to a bit before an instance of the failure, and for a bit afterward.

(In other words, since it's continuously rebuilding, please capture 1-2 builds, so we can try to determine, from the logs, what is triggering it.)

Thanks in advance,

-Dave

**Comment by ysabri** [comment]
Hi,

Yes I will gladly do that, I'm excited to try and fix this together. 

Just one thing before I create the issue, how I do I capture logs and from where exactly?

**Comment by CodeMonk** [comment]
They are usually in `/var/log/jenkins/` on unix-ish operating systems.
