### ISSUE TITLE
Multiple builds kicked off by single pull request

### ISSUE THREAD

**Issue by bmannix** [nishio-dens/bitbucket-pullrequest-builder-plugin#14]
PROBLEM:

Extra builds are being kicked off by a pull request.  These builds are being incorrectly associated with the pull request in bitbucket comments.  While the "real" pull request commit is indeed eventually built, it is not associated with the pull request.

The commits built are often of extra branches, that maybe have new refs since the jenkins job last ran, but are not involved in the pull request.

Is there anything I can do to help debug this?

**Comment by Ingwar** [comment]
Hello! I have encountered problem that looks like yours. Could you, please, describe what misconfiguration it was?

**Comment by bmannix** [comment]
This was a while ago, but I believe is was due to the following piece of the directions being misconfigured:

Add Repository URL as bellow
git@bitbucket.org:${repositoryOwner}/${repositoryName}.git
In Branch Specifier, type as bellow
*/${sourceBranch}

I replaced the variables with static values and it turns out what you need is *exactly* what is written (e.g. source branch = */${sourceBranch}  )

**Comment by Ingwar** [comment]
Thank you, I have set the the branch specifier to the  */${sourceBranch} and it helped.

P.S.
I just noticed that it was in README all this time :)
