### ISSUE TITLE
Does this plugin work with BitBucket Server?

### ISSUE THREAD

**Issue by davetherave112** [nishio-dens/bitbucket-pullrequest-builder-plugin#140]
...formerly known as Stash, the self-hosted bitbucket server.

**Comment by arthurbarros** [comment]
wonder the same

**Comment by JavierLight** [comment]
+1

**Comment by bblain7** [comment]
+1
Looks like the bitbucket.org url is hardcoded. It would be nice if the destination url was an input instead.

**Comment by CaoimhinKing** [comment]
+1, any further information on this would be nice

**Comment by gCardinal** [comment]
+1

This plugin looks like it could pretty much do everything I need.

**Comment by CodeMonk** [comment]
That's a great idea - marking this as an enhancement.

**Comment by CodeMonk** [comment]
Duplicate of #167
