### ISSUE TITLE
BBPRB - total rewrite with webhooks

### ISSUE THREAD

**Issue by ip1981** [nishio-dens/bitbucket-pullrequest-builder-plugin#141]
Guys, I could not wait for this :)

https://github.com/ip1981/bbprb

**Comment by MarcoLotz** [comment]
@ip1981 any idea of when are you going to do a pull request to merge with this repo?

**Comment by ip1981** [comment]
Never?

**Comment by CodeMonk** [comment]
@ip1981 I love the trigger!

Why did you need to rewrite? Do you think it would be possible to add your trigger work here? 

I know many of us are getting lots of 429s from atlassian as they throttle, and, since we poll . . . . it's not getting any better.

**Comment by ip1981** [comment]
> Why did you need to rewrite? Do you think it would be possible to add your trigger work here?

I needed webhooks and something to start with. This plugin, or another (like `bitbcuket`), or from scratch, or port `ghprb`. This plugin was the simplest. There is not much code from this plugin left in `bbprb`, AFAIK only Bitbucket API classes (shrunk too). So I don't think it makes sense to "port" it back here.

**Comment by CodeMonk** [comment]
Closing since not an "issue"
