### ISSUE TITLE
Status check in bitbucket still shows as failed, even though a later build has passed

### ISSUE THREAD

**Issue by ilyache** [nishio-dens/bitbucket-pullrequest-builder-plugin#143]
EDIT: Classic, happened due to a misconfiguration. Sorry for this. We can close the issue.
---
There's information about why this happens here:
https://confluence.atlassian.com/bitbucketserverkb/commit-build-status-is-always-red-even-if-other-builds-succeed-779171240.html

**Comment by CodeMonk** [comment]
@ilyache Nice! I get to close one!
