### ISSUE TITLE
Cancel outdated jobs not working correctly

### ISSUE THREAD

**Issue by jethrogb** [nishio-dens/bitbucket-pullrequest-builder-plugin#146]
I recently enabled "Cancel outdated jobs". Whenever any commits are pushed to a branch for any PR, all outstanding jobs are cancelled, instead of just the ones associated with the relevant PR.

**Comment by CodeMonk** [comment]
@jethrogb Is this still happening? I believe it may have been fixed.

**Comment by CodeMonk** [comment]
Closing due to lack of followup
