### ISSUE TITLE
Plugin is sometimes checking out the wrong branch

### ISSUE THREAD

**Issue by exi** [nishio-dens/bitbucket-pullrequest-builder-plugin#15]
From time to time, we have the plugin checking out the wrong branch which does not match the pullrequest it is building.

The messages like:
[BuildFinished] 35ab5c2fd6da 
Displays the right commit sha1 but the actual build is done on another wrong commit.

For example we have a build stating:

[BuildFinished] 35ab5c2fd6da
:x:FAILURE - http://myhost/job/on%20pull%20request%20integration%20tests/145/

But if i click on the link, the Jenkins says:
Revision: "70999cf314ef889e6167c2a103cf9030cb621580"
Which is obviously wrong.

I am having trouble reliably reproducing this problem but one it occurs, even posting "test this please" on the pull request checks out and tests the wrong commit again.

The problem is usually resolved by "bumping" the pull request with a new commit.

**Comment by paulintrognon** [comment]
Same problem here =(

Would love some to have it fixed =)

**Comment by exi** [comment]
@paulintrognon for a workaround, just check out the production branch on this repo:
https://github.com/exi/bitbucket-pullrequest-builder-plugin/tree/production
Compile it with 'mvn package' and use the resulting hpi file in your Jenkins.
This problem is fixed there.

**Comment by ghusse** [comment]
Is it possible to merge this modification back to this repo? The problem appears very often in our case.
