### ISSUE TITLE
Update 1.4.26 breaks multiple git clone in pipeline

### ISSUE THREAD

**Issue by Aamir010** [nishio-dens/bitbucket-pullrequest-builder-plugin#152]
I have a pipeline which try git clone on two different nodes. And it's cloned sourceBranch git but when it tried to clone another git repo then it will used a commit id of sourceBranch, Here's the below log trace.

[Pipeline] deleteDir
[Pipeline] checkout
02:01:21 Cloning the remote Git repository
02:01:21 Cloning repository git@bitbucket.org:mycompany/core.generic.git
02:01:21  > git init c:\dev\workspace\aamir-core-generic@2 # timeout=10
02:01:21 Fetching upstream changes from git@bitbucket.org:mycompany/core.generic.git
02:01:21  > git --version # timeout=10
02:01:21 using GIT_SSH to set credentials 
02:01:21  > git fetch --tags --progress git@bitbucket.org:mycompany/core.generic.git +refs/heads/*:refs/remotes/origin/*
02:01:30  > git config remote.origin.url git@bitbucket.org:mycompany/core.generic.git # timeout=10
02:01:30  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
02:01:31  > git config remote.origin.url git@bitbucket.org:mycompany/core.generic.git # timeout=10
02:01:31 Fetching upstream changes from git@bitbucket.org:mycompany/core.generic.git
02:01:31 using GIT_SSH to set credentials 
02:01:31  > git fetch --tags --progress git@bitbucket.org:mycompany/core.generic.git +refs/heads/*:refs/remotes/origin/*
02:01:33  > git rev-parse "327ef86f5edd^{commit}" # timeout=10
02:01:33  > git branch -a -v --no-abbrev --contains 327ef86f5eddb632a4c57195902a02267b5d7a58 # timeout=10
02:01:33 Checking out Revision 327ef86f5eddb632a4c57195902a02267b5d7a58 (origin/DO-2227)
02:01:33  > git config core.sparsecheckout # timeout=10
02:01:34  > git checkout -f 327ef86f5eddb632a4c57195902a02267b5d7a58
02:01:34 Commit message: "test123 edited online with Bitbucket"
[Pipeline] dir
02:01:34 Running in c:\dev\workspace\aamir-core-generic@2\Automation
[Pipeline] {
[Pipeline] checkout
02:01:35 Cloning the remote Git repository
02:01:36 Cloning repository git@bitbucket.org:mycompany/cd.git
02:01:36  > git init c:\dev\workspace\aamir-core-generic@2\Automation # timeout=10
02:01:36 Fetching upstream changes from git@bitbucket.org:mycompany/cd.git
02:01:36  > git --version # timeout=10
02:01:36 using GIT_SSH to set credentials 
02:01:36  > git fetch --tags --progress git@bitbucket.org:mycompany/cd.git +refs/heads/*:refs/remotes/origin/*
02:01:42  > git config remote.origin.url git@bitbucket.org:mycompany/cd.git # timeout=10
02:01:42  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
02:01:42  > git config remote.origin.url git@bitbucket.org:mycompany/cd.git # timeout=10
02:01:43 Fetching upstream changes from git@bitbucket.org:mycompany/cd.git
02:01:43 using GIT_SSH to set credentials 
02:01:43  > git fetch --tags --progress git@bitbucket.org:mycompany/cd.git +refs/pull-requests/*/from:refs/remotes/*
02:01:45  > git rev-parse "327ef86f5edd^{commit}" # timeout=10

hudson.plugins.git.GitException: Command "git rev-parse "327ef86f5edd^{commit}"" returned status code 128:
stdout: 327ef86f5edd^{commit}

stderr: fatal: ambiguous argument '327ef86f5edd^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

**Comment by dbugrimov** [comment]
It breaks "shared libraries" as well. When it tries to load shared library external source control repositories (Git) I see the same issue:

```
Loading library utils@develop
Attempting to resolve develop from remote references...
 > git --version # timeout=10
using GIT_ASKPASS to set credentials JIRA and Bitbucket
 > git ls-remote https://****.git # timeout=10
Found match: refs/heads/develop revision f2ee2178e7b32dd4d7cfe7a8c368c2cba1f08667
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://****.git # timeout=10
Fetching without tags
Fetching upstream changes from https://*****.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials ****
 > git fetch --no-tags --progress https://****.git +refs/heads/*:refs/remotes/origin/*
 > git rev-parse 1d4acb7d9e17^{commit} # timeout=10
[Pipeline] }
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
hudson.plugins.git.GitException: Command "git rev-parse 1d4acb7d9e17^{commit}" returned status code 128:
stdout: 1d4acb7d9e17^{commit}

stderr: fatal: ambiguous argument '1d4acb7d9e17^{commit}': unknown revision or path not in the working tree.
```

**Comment by jeansergegagnon** [comment]
I see this issue as well. Even if I set the shared library to explicit load and comment out the library command in the pipeline script, it still wants to checkout the library with the commit hash from the pull request instead of master.

Obviously, this is incorrect as it's not even the same repo

**Comment by Aamir010** [comment]
I got the workaround on this issue.
I have used skipDefaultCheckout() in Option section which won't let the source repo clone at every stage by default

**Comment by jeansergegagnon** [comment]
> I got the workaround on this issue.
> I have used skipDefaultCheckout() in Option section which won't let the source repo clone at every stage by default

Doesn't that mean though that the job would never get new code from those other repos? In our case, if we change the shared library code or the jenkinsfile code, we always would want newest code from either of those.

For us, we used a pair of jobs to work around it - the parent job only has the bitbucket pull request builder in it and all it does is call the other job with the build() step. Not ideal, but it works as the job that is recorded in Bitbucket against the commit is the parent job which has no console output.

**Comment by jeansergegagnon** [comment]
> When you mention a stage in your pipeline it will automatically clone the parent repo by default at each and every stage but when you used "skipDefaultCheckout()" it will stop cloning on each and every stage instead it gives you a control whether you wanted to clone it on stage or not.
> And if you used shared library then you have to introduce a helper function where you can pass a clone URL on that function call as a parameter, and you can call that function on a specific stage where you requires your repo to be cloned.

I'm not sure if this applies to us - can you give example pipeline code?

**Comment by Aamir010** [comment]
pipeline {
  agent {
    node {
      label 'Jenkins Slave Client'
    }
  }
  parameters {
      string(name: 'RepositoryName', defaultValue: 'NULL', description: 'RepositoryName')
      string(name: 'PullRequestNumber', defaultValue: 'NULL', description: 'PullRequestNumber')
      string(name: 'DestinationBranch', defaultValue: 'NULL', description: 'DestinationBranch')
      string(name: 'SourceBranch', defaultValue: 'NULL', description: 'SourceBranch')
  }
  options {
    buildDiscarder(logRotator(numToKeepStr:'30', artifactNumToKeepStr:'30'))
    timestamps()
    skipDefaultCheckout()
    disableConcurrentBuilds()

  }

  stages {
    stage ('Code Checkout') {
      steps {
        script {
              def GIT_BRANCH_LOCAL = "${params.DestinationBranch}" - "origin/"
              echo "Source --- ${params.SourceBranch}"
              echo "Destination --- ${params.DestinationBranch}"
              env.GIT_BRANCH_LOCAL = GIT_BRANCH_LOCAL
        }
        deleteDir()
        checkout([$class: 'GitSCM', branches: [[name: "${params.DestinationBranch}"]], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: "${env.WORKSPACE}"]], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'fb565fc96-9d8d0-416r5-984b2-8ee3f02ec1dd4', url: 'git@bitbucket.org:your_user/generic.git']]])
      }
      post {
        failure {
          echo "Build Step Failed"
        }
      }
    }
    stage ('Code Compilation') {
      steps {
        powershell '.\\build.ps1 -target "xUnit" -Configuration "CodeAnalysis"'
        stash includes: 'Generic.Libs.*.nupkg', name: 'Package.Generic'
      }
      post {
        failure {
          echo 'Build Step Faild'
        }
      }
    }
    stage ('Integration Test') {
      agent {
        node {
          label 'Client-Integration-Test'
        }
      }
      steps {
        script {
          checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: "${env.WORKSPACE}\\Automation"]], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'fb5658f96-9d802-41654-98b2s-8ese302ec1dd4', url: 'git@bitbucket.org:your_user/your_repo.git']]])
        }
        dir("${env.WORKSPACE}\\Artifacts"){
          deleteDir()
          unstash 'Package.Generic'
        }
      }
    }
  }
}

**Comment by thunder-spb** [comment]
Got hit by the same bug for Shared library in Scripted Pipeline.
Ver. 1.4.30
Defining 
```
node {
  skipDefaultCheckout()
}
```
doesn't work for me...

**Comment by Aamir010** [comment]
You don't have to use skipDefaultCheckout() because default checkout functionality is of declarative pipeline and you don't have to put this option on scripted pipeline

**Comment by Aamir010** [comment]
By default on scripted pipeline jobs, you will need to explicitly do a checkout step on each stage, so by default on a scripted pipeline, the checkout step is skipped for each step.

**Comment by thunder-spb** [comment]
Thanks for the answer @Aamir010 . How it could be implemented for shared library which invoke git checkout by itself at the begining? 

```
@Library('jenkins-pipeline-shared@master') _
...
node(label) {
...
}
```

**Comment by Aamir010** [comment]
I don't have code handy but you have a separate function in your shared library which takes a git URL and workspace location as an argument . And you can always call that function when you have to checkout the code
