### ISSUE TITLE
Completion message not being sent as Jenkins URL appears null empty upgrade to 2.141

### ISSUE THREAD

**Issue by mjblue** [nishio-dens/bitbucket-pullrequest-builder-plugin#155]
Hi,

I have been using this plugin successfully for a long time now but today we upgraded to Jenkins 2.141. However now this no longer works due to getURL failing it now reports:

Sep 03, 2018 5:44:24 PM bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketBuilds onCompleted
WARNING: PLEASE SET JENKINS ROOT URL IN GLOBAL CONFIGURATION FOR BUILD STATE REPORTING

The equivalent code in console also reports empty:

JenkinsLocationConfiguration globalConfig = new JenkinsLocationConfiguration();
println globalConfig.getUrl()

This looks like a jenkins core change has broken this or a deprecated function is being used?

**Comment by mjblue** [comment]
ah just found the equivalent bug in jenkins issuetracker, with a potential fix unsure which place we should be tracking this:

https://issues.jenkins-ci.org/browse/JENKINS-53331

**Comment by mjblue** [comment]
Thanks @wrvdklooster  I have taken your fix and opened a PR here: https://github.com/nishio-dens/bitbucket-pullrequest-builder-plugin/pull/156 build is successfully and I am also using this in Jenkins 2.141 successfully now. The only bit I'm confused about it why it stopped working, couldn't see anything obvious in core jenkins changelogs

**Comment by wrvdklooster** [comment]
I checked git changes for JenkinsLocationConfiguration and they changed the constructor. Seems previously get was there and could be used but using constructor also worked. That is how I worked out the fix.

Thanks for the PR. Hope it gets integrated soon. Until then we are using a fork.

**Comment by artstalker** [comment]
Hi. Do you have any plans to release a new version with this fix?

**Comment by CodeMonk** [comment]
I have just come on as a maintainer to help out.

My first goal is to get approved PRs merged, then kick off a release for the official plugin . . . There should be a new plugin out soon (let's say, within a week, since I still have no idea what I'm doing)

:-)

**Comment by CodeMonk** [comment]
I'm going to go ahead and close this issue since it's fix has been merged, just not released.

**Comment by mjblue** [comment]
> I have just come on as a maintainer to help out.
> 
> My first goal is to get approved PRs merged, then kick off a release for the official plugin . . . There should be a new plugin out soon (let's say, within a week, since I still have no idea what I'm doing)
> 
> :-)

Thanks CodeMonk.. and thanks for coming on to help.. ( I have an email in my drafts to Martin to Volunteer to help also but it looks like it's now in hand....)

Mark

**Comment by CodeMonk** [comment]
@mjblue Come join the party! The more the merrier!

**Comment by hugoduraes** [comment]
@CodeMonk it's great that you've joined as a maintainer, kudos for you! :)

**Comment by CodeMonk** [comment]
@hugoduraes We are stabilizing master right now, with most PRs and issues closed and/or merged. I expect the last couple of issues to trickle in over the next couple of days.

Then, we get to see what went into the jenkinsci repo, since I've seen some PRs get merged there that did NOT come from this repo, so, we may have an ugly back merge . . good times.

Finally, we will do _______ (Still don't know what I'm doing) so that we get a new release out. 

After that, my priority is adding a trigger model, instead of polling, since polling causes atlassian to throttle, and throttling is probably the biggest pain point in the issues I've seen.
