### ISSUE TITLE
need to refactor all bitbucket v1 api endpoint to v2.

### ISSUE THREAD

**Issue by chrisLeeTW** [nishio-dens/bitbucket-pullrequest-builder-plugin#160]
actually all bitbucket 1.0 APIs will be removed from the REST API permanently on 31 December 2018. (https://confluence.atlassian.com/bitbucket/version-1-423626337.html)

so refactoring is necessary & here is my PR (#159 ) ~~~

**Comment by CodeMonk** [comment]
Thank you!!!!!

I'll make sure it gets merged soon!

**Comment by rajasilambu** [comment]
@CodeMonk Have this been implemented? I am currently having  version 1.4.30. The plugin is currently calling REST API version 1.0. is there any configuration which I can change to make the plugins call REST API 2.0.
