### ISSUE TITLE
jenkins.util.Time - Thread Stuck

### ISSUE THREAD

**Issue by aaclaydb** [nishio-dens/bitbucket-pullrequest-builder-plugin#180]
Building Jobs periodically seems the break due to the bitbucketpullrequestbuilder plug-in using the jenkins.util.Time thread.  This prevents all jobs from building periodically until a restart is performed.

**Comment by CodeMonk** [comment]
Did you identify what in the thread is causing the hang?

**Comment by kuldazbraslav** [comment]
I believe this is the same problem as described here: https://issues.jenkins-ci.org/browse/JENKINS-37632

**Comment by kuldazbraslav** [comment]
I upgraded to version 1.4.28 which stopped using old bitbucket API and it seems to be working so for. Not sure if it's really fixed or just coincidence, I actually think the newer API version is served with lower latency not causing any hangs.

**Comment by fehmicansaglam** [comment]
Not for me. I was also using the version 1.4.28. Sometimes it kept working even for 24 hours, then suddenly stopped.

**Comment by fehmicansaglam** [comment]
Hello. Any updates about this issue?

**Comment by CodeMonk** [comment]
@fehmicansaglam PR for release is up on jenkinsci repo. As soon as it's approved and merged, I'll push out a  new version, 1.4.29. Depending on how long it takes for approvals, it should be out today or tomorrow.
