### ISSUE TITLE
[Feature Request]Make it possible to cancel pending builds on pull request update.

### ISSUE THREAD

**Issue by halfcrazy** [nishio-dens/bitbucket-pullrequest-builder-plugin#181]
When we update force push a pull request, a new build job will enqueue, and the previous build job may be useless.  
If there is a configuration for this will help.

**Comment by CodeMonk** [comment]
Heh - sorry for the slow response, but, I assume you figured out that is exactly what happens, if you have the configuration set to do it.

But, keep in mind, depending on the job, it could still take a while for the job to be killed.
