### ISSUE TITLE
Issue with the new release i.e 1.4.29

### ISSUE THREAD

**Issue by Aamir010** [nishio-dens/bitbucket-pullrequest-builder-plugin#188]
Hello,

We have tried the new release in our production Jenkins and encounters below problems.

1. Still scheduler stop working but this won't impacted any of our other job that does not use bitbucket pull request builder. ( Previously all the jobs are impacted )
2. A feature called "Cancel Outdated Job" is not working.

**Comment by stevemuskiewicz** [comment]
Hello,

We are seeing a similar issue in our Jenkins environment, it appears that the "cancel outdated job" is not working as it did before with 1.4.28.  The plugin appears to be posting a "build running" status on the latest commit but it doesn't point to an actual Jenkins job (only the Jenkins main URL) and the job based on the new commit is never triggered.

**Comment by CodeMonk** [comment]
I am currently working on these issues. They all seem to stem from some last minute changes in #147.

**Comment by CodeMonk** [comment]
PR #191 should address - feel free to try it out.

**Comment by CodeMonk** [comment]
About to push a release -- closing this.

**Comment by stevemuskiewicz** [comment]
This doesn't seem to be addressed fully, we are still seeing weird build status that don't link to anything and outdated builds are not being cancelled, see #193
