### ISSUE TITLE
Job name incorrectly displayed on Bitbucket PR page

### ISSUE THREAD

**Issue by JosephThomasParker** [nishio-dens/bitbucket-pullrequest-builder-plugin#189]
On the Bitbucket pull request page, the pop-up list of builds used to display the job name as set in the "CI Name" field on Jenkins configure.  Since the last plugin release, it instead displays a much-less-meaningful hash.  The hyperlink still points to the correct job; it's just the display name that's wrong.

**Comment by CodeMonk** [comment]
Found bug in #147 - Looks like the abstraction got broken and started favoring server in several cases.

I'm working on a fix that I will test against cloud.

**Comment by CodeMonk** [comment]
PR #191 should address - feel free to try it out.

**Comment by CodeMonk** [comment]
Pushing a release now, so closing this.

**Comment by JosephThomasParker** [comment]
Thanks!  (I don't run the server, so I haven't checked the fix)

**Comment by CodeMonk** [comment]
Actually, the Server changes broke Cloud support - so, this bug has affected only Cloud users, not Server users.

**Comment by JosephThomasParker** [comment]
Ah, I meant the Jenkins server - I can't update plugin... instead I just send hopeless emails to sysadmins...

**Comment by CodeMonk** [comment]
No worries -- it will auto-update in a few days (after PR, after merge, after release, and after it slowly trickles out)
