### ISSUE TITLE
Cancel outdated job not working

### ISSUE THREAD

**Issue by mokone91** [nishio-dens/bitbucket-pullrequest-builder-plugin#194]
Hi, after the last update "Cancel outdated job" feature not working anymore..

I use pipeline script 
Here example:

```
#!/usr/bin/env groovy
properties([disableConcurrentBuilds()])
pipeline {
    agent any
    tools { nodejs "nodejs" }
    environment {
        NODE_ENV = 'tests'
    }
    options {
        timestamps()
    }
    triggers {
        bitbucketpr(
            projectPath: 'git@bitbucket.org:***/***.git',
            cron: '* * * * *',
            credentialsId: '****',
            repositoryOwner: '***',
            repositoryName: '***',
            branchesFilter: '',
            branchesFilterBySCMIncludes:false,
            ciKey: 'jenkins-tests',
            ciName: 'Jenkins tests',
            ciSkipPhrases: 'trivial,[skiptest],[trivial]',
            checkDestinationCommit: false,
            approveIfSuccess: false,
            cancelOutdatedJobs: true,
            commentTrigger: 'test this please'
        )
    }
    stages {
        stage("Install dependencies") {
            steps {
               sh "yarn"
            }
        }
        stage("Deploy to remote server") {
            steps {
              sshagent(credentials : ['******']) {
                  sh "yarn deploy"
              }
            }
        }
        stage("Run Tests") {
            steps {
               sh "yarn test"
            }
        }
    }
    post {
          always {
            junit 'packages/test/reports/report.xml'
          }
       }
}
```

**Comment by mokone91** [comment]
Hi again!
In version 1.4.26 this feature works great, but bitbucket do not update build status(

**Comment by mokone91** [comment]
I tested latest version on clear jenkins installation also, issue still presented

**Comment by znerd** [comment]
@mokone91 : It would be useful if you could elaborate on which version of the Bitbucket PR Builder Plugin was still working fine, and which version introduced the bug you describe.

Additionally, it would be helpful to share your Jenkins version.

Regarding your credentials: are you filling _both_ the `credentialsId` as well as the user name + password combination?

**Comment by CodeMonk** [comment]
There was a bug that went in that broke job canceling. That should be fixed.

If you are seeing issues, please provide the logs, too, and the exact version you're running.

I did have issues pushing out the last release. Perhaps it didn't grab the new changes?

**Comment by jekkata** [comment]
Hi i have the same issue `cancelOutdatedJobs` feature not working. 
Use jenkins version 2.190.1 with plugin version 1.5.0 and 1.4.30 

```
triggers{
        bitbucketpr(
            projectPath:'',
            cron: '* * * * *',
            credentialsId: 'Bitbucket',
            username: '******',
            password: '*****',
            repositoryOwner: '****',
            repositoryName: '*****',
            branchesFilter: 'trivial,[skiptest]',
            branchesFilterBySCMIncludes: false,
            ciKey: 'jenkins',
            ciName: 'Jenkins',
            ciSkipPhrases: '',
            checkDestinationCommit: false,
            approveIfSuccess: false,
            cancelOutdatedJobs: true,
            commentTrigger: 'test this please'
        )
    } 
```

**Comment by CodeMonk** [comment]
Thanks for providing the versions, but, without logs . . . . I'll try some code inspection this weekend, but, I wouldn't hold your breath.

**Comment by jekkata** [comment]
My problem is that, when `cancelOutdatedJobs` option is enabled and programmer push new code does not stop old running job in Jenkins to start a new one with least version of code.

**Comment by CodeMonk** [comment]
Jobs in jenkins do not stop immediately. Sometimes steps can take many minutes to catch the abort signal.

I'd be happy to analyze any logs you can attach, but, without logs, there is really nothing more I can do.

**Comment by CodeMonk** [comment]
Closing since this is not the same issue that was fixed, and there are no logs to analyze to see if a different error is occurring.
