### ISSUE TITLE
Programatically placing comment on pull request through pipeline api

### ISSUE THREAD

**Issue by JasonDictos** [nishio-dens/bitbucket-pullrequest-builder-plugin#218]
Does this plugin provide a pipeline api to programatically add a comment on a pr? I'm doing some custom things with our internal docker deployments, part of it is 'staging' our webapp at a url, I'd like to 'post' this comment on the open pr.

Additionally I'd like to programatically do something when the pr is detected as being deleted (in this case, I'd like to un-stage the webapp for the given pr).

Anyway to do that with this plugin? Maybe I can use this plugin as an example for a custom one...

**Comment by CodeMonk** [comment]
No, but the bitbucket plugin might.

Feel free to submit something if you end up extending this plugin!
