### ISSUE TITLE
Personal access tokens

### ISSUE THREAD

**Issue by kuhnboy** [nishio-dens/bitbucket-pullrequest-builder-plugin#221]
Does this support Personal access tokens vs username/password?

**Comment by CodeMonk** [comment]
I'm pretty sure a jira personal access token just does basic auth, and, I
also think the username/password is basic auth, so, in that case it should
work if bitbucket does the same thing.

But, if you're talking about the normal token-only authentication, no, the
plugin does not support that type of login.
