### ISSUE TITLE
Build links not displayed on BitBucket Server 7.0+

### ISSUE THREAD

**Issue by rmichalak** [nishio-dens/bitbucket-pullrequest-builder-plugin#223]
Build links are not displayed on BitBucket Server, as per attached screenshot:
![image](https://user-images.githubusercontent.com/8317772/82903389-2800b300-9f61-11ea-8d5a-af0d8a4023e8.png)

It seems that 'name' and 'description' are missing from requests (which is not the case for BitBucket Cloud)
Proposed fix is to align request with Cloud version: https://github.com/rmichalak/bitbucket-pullrequest-builder-plugin/commit/09a67c4f3a2cfe4a0f4d5d9f6f5585687e48834f although I'm not sure if it won't break anything for older BitBucket Server versions.

**Comment by rmichalak** [comment]
More info: The problem only exists when reviewing particular pull request, not on a list of all pull requests. In both cases BitBucket returns the same response but 'key' is only used to display a link on a list of PRs.
It seems like a bug in BitBucket Server (7.0.3) itself, nevertheless I think it still would be good to include 'name' and 'description' in updates, to line it up with the cloud version.

**Comment by CodeMonk** [comment]
Sorry - only one person that I know of is using / supporting the server
side, so, bugs there are completely normal :(

The fix looked good to me at first glance, please put up a PR to
nishio-dens' repo, and I'll merge ASAP!

-Dave

**Comment by rmichalak** [comment]
No worries, I'm here to help ;)
Patched version works in our infrastructure without any problems for over two weeks now.

**Comment by CodeMonk** [comment]
Merged - will be in next release.
