### ISSUE TITLE
Bitbucket Pullrequest Builder page- Does this support for bitbucket Datacenter

### ISSUE THREAD

**Issue by ManjunathRNayak** [nishio-dens/bitbucket-pullrequest-builder-plugin#225]
Hi Team,
As mentioned in the Doc the following line states that this plugin will be able to connect to bitbucket.org (cloud).
"This plugin builds pull requests from Bitbucket.org and will report the test results. Basic documentation can be found on GitHub."
Can you confirm on this that if this supports the same functionality with bitbucket datacenter as same as it functions with bitbucket cloud?

Thanks in advance.

Regards,
Manjunath R

**Comment by ManjunathRNayak** [comment]
Does it support with Bitbucket Server(Hosted on-premise)?

**Comment by CodeMonk** [comment]
Two people that I know are using it with Bitbucket Server. One just
submitted a PR.

**Comment by ManjunathRNayak** [comment]
thanks for the clarifications
