### ISSUE TITLE
Automated PR builds selects source branch for pipeline scam checkout

### ISSUE THREAD

**Issue by hrushie** [nishio-dens/bitbucket-pullrequest-builder-plugin#226]
Hello Team,

We are using Jenkins Pipeline and automated Bitbucket PR builds. but our source branches have different jenkins files and than our normal jenkins branches. how can I fix this issue?

**Comment by CodeMonk** [comment]
I'm sorry, but could you provide more detail or rephrase? I don't understand what you're asking.
