### ISSUE TITLE
log files?

### ISSUE THREAD

**Issue by knlr** [nishio-dens/bitbucket-pullrequest-builder-plugin#230]
I have installed this plugin and added it to my build. It doesn't seem do anything. I have no idea what's going on. Where can I check? There doesn't seem to be anything in my jenkins log file

**Comment by knlr** [comment]
apologies, Jenkins rookie here. Found it in Jenkins status / logs eventually.

**Comment by CodeMonk** [comment]
Sorry for the late reply, I fall behind in email sometimes, and I missed
this one.

Checkout the documentation. It's terrible, but, the setup docs do work.
Please LMK if you have issues after following those instructions. I promise
to respond faster next time!
