### ISSUE TITLE
Build messages from multiple projects conflict with each other

### ISSUE THREAD

**Issue by csakoda** [nishio-dens/bitbucket-pullrequest-builder-plugin#25]
I ran into an issue in my jenkins setup where I wanted to have two jenkins projects targeting a single bitbucket repo using the pull request plugin.  I noticed that only one of the projects was getting build on each PR update.  It looks like because the each project's plugin is looking for the same messages, like

```
[BuildFinished] 8a5d444cdf1f into 169ebf1e2024
```

the second project decides theres a build already in progress and doesn't fire.  But that's the build for the _first_ project.

The messages should be uniquely tied to each project, I suggest adding the project name to the build messages.  I have a pull request implementing that.

**Comment by jacoor** [comment]
I have a feeling this issue is back. I am using version 1.4.16 and it triggers only first job (alphabetically). I am downgrading to earlier version right now, as that version worked before.

@nishio-dens  FYI.

**Comment by maxvodo** [comment]
Yep, at this moment we don't using `jenkins project id` or similar project identifier to check pr build status.

**Comment by jacoor** [comment]
I have a weird experience with this.
I have two almost the same projects (difference is bb url) with two jobs on each. Funny thing:
- on one project two jobs run w/o problem
- on second one only the first job (alphabetically) runs. 
No idea right now what is happening.

**Comment by maxvodo** [comment]
@jacoor I checked out code deeper and there is available additional `project id` identifier in check build status function.
`ApiClient::hasBuildStatus()` uses MD5 of `project.getFullName()` [here](https://github.com/nishio-dens/bitbucket-pullrequest-builder-plugin/blob/master/src/main/java/bitbucketpullrequestbuilder/bitbucketpullrequestbuilder/BitbucketRepository.java#L229).

I am understand right, that "One project with two jobs" it's a job with two sub-jobs in build (or post-build actions), right?

**Comment by jacoor** [comment]
Hi @maxvodo thank you for looking into this. 
To have the information clear, I have two projects in bitbucket on which I use pull requests. Each of the projects has two jenkins jobs, started by pull request builder. On project A those two jobs start without a problem, on project B only first build (alphabetically) starts.
Actions taken:
- verified user passwords
- deleted and created new build based on the one that is working
- changed all the names related to PR builder to be unique
No success. 
LIke I said, it is very weird issue. Right now I have a workaround - I enabled only the most extensive test build, skipping the other one. Any help is greatly apprectiated and I will gladly provide any information that can help solving/reproducing the issue.

**Comment by maxvodo** [comment]
@jacoor Thx you! I need some time for modify code to provide more debug information. Then I build plugin version with this modifications. Afterwards, you can load this plugin into your Jenkins and collect logs.

**Comment by jacoor** [comment]
@maxvodo: another update. This issue is really freaking weird. Right now I have 3 PRs - two old, on which I can't trigger the jobs and one new, created five minutes ago -> both jobs started nicely. I am really confused with this.
