### ISSUE TITLE
PR URL is not displayed correctly in build summary

### ISSUE THREAD

**Issue by mgrebenets** [nishio-dens/bitbucket-pullrequest-builder-plugin#31]
The link back to PR is not formatted as proper HTML and looks like this.
![screen-build-results](https://cloud.githubusercontent.com/assets/350654/5808894/96ca1b80-a086-11e4-88a5-f6641dd77c44.png)

Here's how the HTML page source looks like
``` html
<td class="pane build-details">
<a href="/jenkins/view/Dev/job/Dev-Bitbucket-PR/1/" class="tip model-link inside">Jan 20, 2015 9:20:03 AM</a>
<div class="desc">&lt;a href=https://bitbucket.org/fairfax/mobile-misc-jenkins-job-dsl/pull-request/27>#27 Dummy PR&lt;/a></div>
</td>
```

**Comment by naphthalene** [comment]
Running into this too - I'm not sure hypertext links can be inserted this way.

**Comment by jcbwlkr** [comment]
In your Jenkins configuration go to *Configure Global Security* Then change the option "Markup Formatter" to *Safe HTML*. It defaults to "Escaped HTML" which escapes all of the HTML tags generated by this plugin.

This is a slight lax of security for what I consider a reasonable outcome.

**Comment by mgrebenets** [comment]
Cool, thanks, ti works.
