### ISSUE TITLE
Add support for Credentials plugin

### ISSUE THREAD

**Issue by mgrebenets** [nishio-dens/bitbucket-pullrequest-builder-plugin#33]
https://issues.jenkins-ci.org/browse/JENKINS-24707

Storing password as plaintext is a security risk, and because of this adding Jenkins Job DSL support for Bitbucket Pull Request builder is not possible at the moment https://github.com/jenkinsci/job-dsl-plugin/pull/357.

As far as I understand, with support for Credentials there will be no need for repository owner and repository password fields in plugin configuration, instead SCM credentials are used.

**Comment by Laucsen** [comment]
+1

**Comment by mitchwongho** [comment]
+1
In the interim, can this task be performed with a script?

**Comment by mgrebenets** [comment]
Which task?
If you mean supporting credentials plugin - I don't know if it's possible.

If you want Job DSL plugin with Bitbucket PR builder support, you can always build it off this branch https://github.com/mgrebenets/job-dsl-plugin/tree/mgrebenets/26488-bitbucket-pr-builder.

**Comment by jawshooah** [comment]
:+1: @nishio-dens, are there any plans to implement this?

**Comment by Darhazer** [comment]
+1

**Comment by sazlin** [comment]
+1

**Comment by vladistan** [comment]
:+1:

**Comment by Harenkamp** [comment]
+1
