### ISSUE TITLE
Link to build in bitbucket pullrequest comment

### ISSUE THREAD

**Issue by mkamioner** [nishio-dens/bitbucket-pullrequest-builder-plugin#35]
Hi again!

As I am using this plugin many many times, I am realizing that a link in the pull request comment would be a wonderful tool.

So instead of 
[_BuildStarted_ **myJenkins**] [6a3f23d22c43](https://bitbucket.org/me/myrepo/commits/6a3f23d22c43) into [207459000ea0](https://bitbucket.org/me/myrepo/commits/207459000ea0)

it could be changed to
[_BuildStarted_ **myJenkins** [#123](http://mymagicjenkins.com/job/tester/123/)] [6a3f23d22c43](https://bitbucket.org/me/myrepo/commits/6a3f23d22c43) into [207459000ea0](https://bitbucket.org/me/myrepo/commits/207459000ea0)

I don't know how hard this is, but it would be very helpful and a great feature!

Thanks again for all your help!
Mo

**Comment by vladistan** [comment]
:+1:
