### ISSUE TITLE
Running build manually results in error.  Build params not set.

### ISSUE THREAD

**Issue by tkelley-eg** [nishio-dens/bitbucket-pullrequest-builder-plugin#38]
Running a build from the jenkins console does not seem to result in proper initialization of the plug-in as the variables do not appear to be setup correctly, resulting in:

> git rev-parse refs/remotes/origin/${sourceBranch}^{commit} # timeout=10
> git rev-parse refs/remotes/origin/origin/${sourceBranch}^{commit} # timeout=10

**Comment by brouberol** [comment]
I'm also affected by this. It appears the ``sourceBranch`` and ``targetBranch`` environment variables are only set when the plugin polls for new pull requests and finds one, not when a build is triggered manually. 

For info, I'm trying to setup my jenkins job to build
* new pull requests
* the master branch, if the job is ran manually

Is it possible to somehow set ``targetBranch`` and ``sourceBranch`` as ``master`` by default, which would get overriden in the case of a PR build?

**Comment by fonsecas72** [comment]
I think you can add parameters.
I got ```sourceBranch``` ```repositoryOwner``` ```repositoryName``` and ```targetBranch``` parameters.

**Comment by brouberol** [comment]
You mean add parameters to the jenkins build itself, via the "This build is parameterized" tick?

**Comment by fonsecas72** [comment]
Yes

**Comment by brouberol** [comment]
You sir, made my day. Thanks!

**Comment by fonsecas72** [comment]
@tkelley-eg did my solution work for you too?

**Comment by tkelley-eg** [comment]
@fonsecas72, I could add sourceBranch param, but that would take away the dynamic nature of the build, correct?  I would like to run the build manually to query for a pull request and build it.

**Comment by fonsecas72** [comment]
oh I see, that is in fact another issue. I don't know if that'l be easy to implement though :/
This plugin would have to add another button for this purpose I suppose.

**Comment by dzschille** [comment]
Isn't the purpose of this plugin to trigger a build when there is a pull request in Bitbucket? So instead using the build button, i write as a pull request comment "test this please" to trigger a new build.
