### ISSUE TITLE
Add support for mercurial repos

### ISSUE THREAD

**Issue by PaulRF** [nishio-dens/bitbucket-pullrequest-builder-plugin#42]
Hi, guys
Currently the plugin works with git only. Please, add support for mercurial as well (Jenkins Mercurial plugin: https://github.com/jenkinsci/mercurial-plugin). I tried to use your plugin together with mercurial repo but  the created pull requests are not triggered. I think no reasons to avoid mercurial. Thanks!

**Comment by b-studios** [comment]
On my setup the PRs do also trigger rebuilds with Mercurial. This part of the plugin (at this point) should be independent of Mercurial vs. git. However the build that is triggered does not automatically use the right revision / branch.

## How to enable automatically building Pullrequests with Jenkins, Mercurial and Bitbucket
*(The title is to facilitate googling)*

*Shortstory*: The trick is to use **parametrized builds** 

Create a [parametrized build](https://wiki.jenkins-ci.org/display/JENKINS/Parameterized+Build) utilizing the string-parameter `sourceBranch`, defaulting to branch you want to build by default (for instance `default`).  In the configuration of the above mentioned Mercurial-Plugin select "Revision Type" `Branch` and then set "Branch" to `$sourceBranch`.

The `bitbucket-pullrequest-builder-plugin` (you seriously need a shorter name ;)) will poll for new PRs, then trigger a build setting `sourceBranch` to the corresponding source branch of the PR (also adding some git related information which you can safely ignore), and update your PR with a status message for the build.
