### ISSUE TITLE
HPI given in the installation documentation seems to be outdated.

### ISSUE THREAD

**Issue by SylvG** [nishio-dens/bitbucket-pullrequest-builder-plugin#43]
Does the hpi file you gave in the installation documentation is up to date ?
Because when I install it, I still have the huge SVG emojis in Hipchat, despite the changes merged from PR #41.

If not, is it possible to update it ?

**Comment by nishio-dens** [comment]
Thank you for pointing it out.
I'm sorry, I forgot to update it.

I uploaded new hpi file to http://doc.densan-labs.net/bitbucket-pullrequest-builder.hpi .
And I has released the latest version(version1.4.5).

If there are any problems, please let me know.

**Comment by SylvG** [comment]
Thank you for the update.
It's better now, I don't have huge pictures in HipChat.

But (there is always a "but" ;) ), I think there is an encoding problem somewhere because in BitBucket and in HipChat I don't see "✓ SUCCESS" and "✕ FAILURE" as expected, but "? SUCCESS" and "? FAILURE".

**Comment by fonsecas72** [comment]
> I think there is an encoding problem somewhere because in BitBucket and in HipChat I don't see "✓ SUCCESS" and "✕ FAILURE" as expected, but "? SUCCESS" and "? FAILURE".

The same here.
