### ISSUE TITLE
HTML entities of build status are not correctly shown on Bitbucket

### ISSUE THREAD

**Issue by Mercynary** [nishio-dens/bitbucket-pullrequest-builder-plugin#47]
The HTML entities of the build stati are only shown as question marks on Bitbucket (see picture below).

![utf8-characters](https://cloud.githubusercontent.com/assets/218707/8277555/482b8a7a-18c4-11e5-8e51-61bebd75e524.png)

**Comment by gbasile** [comment]
Same problem for me. Any update?

**Comment by tulku** [comment]
Same here

**Comment by bskart** [comment]
same here

**Comment by Mercynary** [comment]
BTW, it would also be nice to have a status for "unstable" builds.

**Comment by tulku** [comment]
This was probably fixed with https://github.com/nishio-dens/bitbucket-pullrequest-builder-plugin/pull/46.

**Comment by Mercynary** [comment]
No it was introduced by this change/issue.
