### ISSUE TITLE
Variables not being set

### ISSUE THREAD

**Issue by mmazing** [nishio-dens/bitbucket-pullrequest-builder-plugin#53]
The plugin is seeing pull requests and firing, but the build ultimately fails because there are still variable placeholders that aren't being populated by the plugin.

Example - 

```
> git -c core.askpass=true fetch --tags --progress https://username@bitbucket.org/company/testing-jenkins-hooks.git +refs/heads/*:refs/remotes/origin/*
> git config --local --remove-section credential # timeout=10
> git rev-parse 5c4a4041ad32^{commit} # timeout=10
> git branch -a --contains 5c4a4041ad32b569047591c72e656f585ece6c # timeout=10
> git rev-parse remotes/origin/test-branch^{commit} # timeout=10
Merging Revision 5c4a4041ad32b569047591c72e656f585ece6c (origin/test-branch) to testing-jenkins-hooks/master, UserMergeOptions{mergeRemote='testing-jenkins-hooks', mergeTarget='${targetBranch}', mergeStrategy='default', fastForwardMode='--ff'}
> git rev-parse testing-jenkins-hooks/master^{commit} # timeout=10
FATAL: Command "git rev-parse testing-jenkins-hooks/master^{commit}" returned status code 128:
stdout: testing-jenkins-hooks/master^{commit}
```

When I look in the build parameters, there is no "commit" parameter, but there is "targetBranch", although targetBranch isn't being populated. "company" and "testing-jenkins-hooks" are parameters that are being populated correctly.

**Comment by mmazing** [comment]
I've narrowed down the issue a little bit, it has to do with the "Merge before build" option. The {commit} stuff seems to be working OK, but the targetBranch variable isn't being populated.

**Comment by mmazing** [comment]
Little more info, and this doesn't seem to actually be a problem with the bitbucket-pullrequest-builder-plugin. I think the "Merge before build" option is actually a part of the Jenkins GIT plugin, which should normally work correctly, except the ${} variables can't make it into those settings. If there's an easy way to fix that, I would be interested, otherwise, no worries.

**Comment by delconis** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-24133

This seems to be solved in a newer version of the Git Plugin. 2.3.1+

**Comment by awilkening** [comment]
Still seeing this issue with Jenkins 2.5, git plugin 2.4.4, bit bucket pull request build 1.4.18

Just upgraded from Jenkins 1.6.x, not sure about the other plugin versions. These features were working.

As  @mmazing stated, only an issue in the additional behavior of merging before the build, ${targetBranch} is not being evaluated.

**Comment by awilkening** [comment]
I also noticed that before the upgrade, I was able to use ${sourceBranch} in my notices to hipchat, but now they are being printed with the literal value of "The pull request for ${sourceBranch} failed"

**Comment by peetron** [comment]
I am getting the same problem with ${targetBranch} not being evaluated
Jenkins 2.7
git plugin 2.4.4
bit bucket pull request build 1.4.19

**Comment by awilkening** [comment]
@peetron I upgraded to 2.7 and 1.4.19 and my issues were resolved. Try deleting the configuration and recreating it. During my initial upgrade, that seemed to fix some of the problems.

**Comment by peetron** [comment]
@awilkening 
Yep, oops. I see that resolved for me too. I guess I didn't wait for the instance to restart properly after updating the plugin. My mistake.

**Comment by cyberbob25** [comment]
I'm seeing this issue as well.  I'm running the latest Jenkins build (2.21), git plugin version 2.6.0, and bitbucket plugin 1.4.19.  This plugin was running fine on our previous Jenkins installation which was running Jenkins 1.651.

The job fires fine, but the ${pullRequestId} var never gets set:
```
> 09:59:01 [EnvInject] - Loading node environment variables.
> 09:59:01 Building on master in workspace /var/lib/jenkins/workspace/API-PR
> 09:59:01  > git rev-parse --is-inside-work-tree # timeout=10
> 09:59:01 Fetching changes from the remote Git repository
> 09:59:01  > git config remote.origin.url ssh://somehost.somedomain.com/a/api # timeout=10
> 09:59:01 Cleaning workspace
> 09:59:01  > git rev-parse --verify HEAD # timeout=10
> 09:59:01 Resetting working tree
> 09:59:01  > git reset --hard # timeout=10
> 09:59:01  > git clean -fdx # timeout=1009:59:01 Fetching upstream changes from ssh://somehost.somedomain.com/a/api
> 09:59:01  > git --version # timeout=10
> 09:59:01  > git -c core.askpass=true fetch --tags --progress > ssh://somehost.somedomain.com/a/api +refs/pull-requests/*:refs/remotes/origin/pr/*
> 09:59:01  > git rev-parse refs/remotes/origin/pr/${pullRequestId}/merge^{commit} # timeout=10
> 09:59:01  > git rev-parse refs/remotes/origin/origin/pr/${pullRequestId}/merge^{commit} # timeout=10
> 09:59:01  > git rev-parse origin/pr/${pullRequestId}/merge^{commit} # timeout=10
> 09:59:01 ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job```
