### ISSUE TITLE
HTML is not escaped properly

### ISSUE THREAD

**Issue by tnguyen14** [nishio-dens/bitbucket-pullrequest-builder-plugin#59]
Attached are 2 screenshots that describe this problem. The first one is on the builds listing on the left side of the job.
![jenkins-jobs](https://cloud.githubusercontent.com/assets/1652595/9685744/3823fc3e-52ee-11e5-9368-4b64c4d8715b.png)

The second one is on Slack when I integrate with the Slack plugin
<img width="1028" alt="slack notification" src="https://cloud.githubusercontent.com/assets/1652595/9685756/437dbd18-52ee-11e5-8c3f-a9c5e04f3495.png">

**Comment by jwismar** [comment]
There is a Jenkins configuration setting that controls that. It's under "Manage Jenkins > Configure Global Security". There's a drop down labelled "Markup Formatter". Change the setting from "Escaped HTML" to "Safe HTML".

**Comment by tnguyen14** [comment]
I see "Escaped HTML" and "Raw HTML". Is "Raw HTML" the one I'd want?

**Comment by jwismar** [comment]
There must be another setting or plugin that enables the "Safe HTML" option, but I can't find it right now. But yes, I think that the "Raw HTML" setting will fix this problem for you.

**Comment by tnguyen14** [comment]
Is it this plugin https://wiki.jenkins-ci.org/display/JENKINS/OWASP+Markup+Formatter+Plugin?

**Comment by tnguyen14** [comment]
Update: I do have the "OWASP Markup Formatter Plugin" installed. However, it was at version 1.1. When I updated it to version 1.3, the second option appears as "Safe HTML" and not "Raw HTML".

This seems to fix the issue with the builds list. Once I can confirm that the slack notifications are also formatted correctly, I'll close this issue.

**Comment by tnguyen14** [comment]
Just to follow up - the slack notifications are still showing the unescaped HTML. I am not sure if this would be an bug for the Slack plugin repo or for this repo...

**Comment by joshskinner** [comment]
+1 on the slack integrations

**Comment by tnguyen14** [comment]
Related jenkinsci/slack-plugin#126

**Comment by maxvodo** [comment]
Check this later
