### ISSUE TITLE
"Rebuild if destination branch changes" broken with 1.4.8 / Bitbucket Build-Status API

### ISSUE THREAD

**Issue by bskart** [nishio-dens/bitbucket-pullrequest-builder-plugin#67]
Since the upgrade to the latest version (1.4.8) the "Rebuild if destination branch changes" does not work anymore for our builds.

Scenario:
- Inside our PullRequest-Buildjob we are merging the branch under PR into the target-branch.
- We have 3 open PRs against branch develop.

Now one gets merged, this will change the develop-branch and should trigger new builds for the 2 still open PRs, because now they would get merged with a new version of develop, which seems to not happen, because the "commits" of the 2 still open PRs/branches still are marked as passed and therefor no new build is triggered.

This is probably related to how with the Bitbucket Build-Status API it is determined if a Build-Job is run or not: 

https://github.com/nishio-dens/bitbucket-pullrequest-builder-plugin/commit/620a2215e275e124836327ba1e6a153d07615af2#diff-8

> This identifier is used to decide whether a commit is already built by this job and to set status for a newly built commit.

An initial idea I had which might have solved this was to make this identifier "dynamic" so it can contain for example the hash of the commit in the branch it was build against, that would solve the problem that no new build is triggered, but it would then show 2  different build-stati on the build in the Bitbucket  PullRequest which would not really be what i expect.

**Comment by rubao** [comment]
same here, another idea would be to parse the comment from build status "8a7sd8796 into 76sf5g8d8f7" like before using comments in the pull-request. Instead of "98as4d9f84 into master"

**Comment by maszaa** [comment]
What's the status of this issue? Jenkins won't re-build though target branch is changed.
