### ISSUE TITLE
Tokens in repository URL not replaced

### ISSUE THREAD

**Issue by bosilca** [nishio-dens/bitbucket-pullrequest-builder-plugin#68]
I followed the steps from the README to setup a PR build, but my build keeps failing. Digging in the log file I see that the git command is issued without the tokens correctly replaced:

> hudson.plugins.git.GitException: Command "/usr/bin/git -c core.askpass=true fetch --tags --progress git@bitbucket.org:${repositoryOwner}/${repositoryName}.git

The token macro plugin is installed (v1.12.1), and I can confirm that it works as expected for other tokens. As an example, if I replace any of tokens above (repositoryOwner / repositoryOwner) by tokens provided by jenkins itself (such as BUILD_NUMBER), the generated text is indeed correct.

**Comment by anthofo** [comment]
Same problem for me

**Comment by bosilca** [comment]
I update to the new jenkins core (1.644) and the problem persist. I confirmed that a similar setup, for a project hosted on github and using GitHub pull request builder plugin, is behaving as expected (the tokens are correctly replaced).

**Comment by praveen12bnitt** [comment]
I can confirm that the same behavior in jenkins 1.646

**Comment by shawn-mcginty** [comment]
I have this same problem in Jenkins 2.5
