### ISSUE TITLE
-DpullRequestTitle with spaces breaks my grails builds

### ISSUE THREAD

**Issue by Gazer** [nishio-dens/bitbucket-pullrequest-builder-plugin#70]
I found on a grails project that the spaces on pullRequestTitle breaks my builds with :

<pre>
/mnt/jenkins/tools/com.g2one.hudson.grails.GrailsInstallation/2.2.3/grails-2.2.3/bin/grails -DsourceBranch=b-log-error -DdestinationRepositoryName=backend -DpullRequestId=80 -DdestinationRepositoryOwner=someowner -DrepositoryName=backend "-DpullRequestTitle=bug- log a full trace of exeption in friendship service." -DtargetBranch=develop -DrepositoryOwner=someowner -Dgrails.work.dir=/mnt/jenkins/workspace/PR-Checker//target -Dgrails.env=dev2 compile --non-interactive --plain-output --refresh-dependencies
</pre>

<pre>
|Loading Grails 2.2.3
|Configuring classpath
|Running pre-compiled script
Error |
Script not found: Log
</pre>

I've cloned the project on my pc, run the command manually and get the same error. If I remove the "-DpullRequestTitle...." the project build fine : 

<pre>
|Compiling 259 source files
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
..
|Compiling 139 source files
</pre>

Any ideas on how to solve the problem? I don't remember having this problem on my android jobs.

Edit : I found an old grails bug report about this problem https://jira.grails.org/browse/GRAILS-11351

**Comment by maxvodo** [comment]
Hi @Gazer !

Suppose, there is error in Grails build plugin (or something similar to build trigger), not for this plugin.
Cause I see build started with specific for pull request environments, like `repositoryName ... pullRequestTitle`.

But build command string contain strange substring: 
```
... -DrepositoryName=backend "-DpullRequestTitle=bug- log with spaces." ...
```
Right substring looks like: 
```
... -DrepositoryName=backend -DpullRequestTitle="bug- log with spaces." ...
```
