### ISSUE TITLE
The bitbucket-pullrequest-builder plugin doesn't seem to properly close TCP connections

### ISSUE THREAD

**Issue by multani** [nishio-dens/bitbucket-pullrequest-builder-plugin#75]
![2016-02-17-143147_3840x1200_scrot](https://cloud.githubusercontent.com/assets/65311/13111010/ac5caf16-d583-11e5-8421-dad2bb6aee4b.png)

The attached graph shows the state of the TCP connections between our internal Jenkins server and the Internet. I disabled the ``bitbucket-pullrequest-builder`` plugin and restarted Jenkins around 14:05.

As you can see in the graph, most of the left-over connections are in the ``CLOSE_WAIT`` state, which apparently is due to "something" in Jenkins which connects to Bitbucket, get some data, and leave the connection in a half-opened mode. Below is a screenshot of an earlier network dump showing such a communication between our Jenkins machine and Bitbucket (see in particular the ``FIN`` coming from Bitbucket but never from the Jenkins machine itself):

![2016-02-17-144104_3840x1200_scrot](https://cloud.githubusercontent.com/assets/65311/13111230/02068e40-d585-11e5-8cb0-4bfa7e4f24f8.png)

(This is a problem because we got hundreds (apparently thousands if we believe our Internet provider) of very long TCP connections which were exhausting our Internet connection. The connection from the network below shows a connection lasting 7 hours+)

I'm posting this here since deactivating this plugin doesn't exhibit the problem anymore.

(/ping @nmihajlovski who help me to diagnose the issue and who may have more inputs than me on this particular problem)

**Comment by maxvodo** [comment]
@multani @nmihajlovski You may test [build](https://github.com/maxvodo/bitbucket-pullrequest-builder-plugin/releases/tag/bitbucket-pullrequest-builder-fix-issue-75) with fix from #76 pr.

**Comment by multani** [comment]
@maxvodo Thanks for the fix, I'll have a look in the coming days but not now as activating something which such a problem has too many consequences on our current network. I should have safer moments to do it, probably on Monday evening.

**Comment by nishio-dens** [comment]
I merged PR #76.
