### ISSUE TITLE
Expose environment variables

### ISSUE THREAD

**Issue by ghusse** [nishio-dens/bitbucket-pullrequest-builder-plugin#77]
Is it possible to publish environment variables such as Pull Request Id and title? That would be really usefull and allow me to use other plugins with these informations.

The github plugin exposes these variables:

- ghprbActualCommit
- ghprbActualCommitAuthor
- ghprbActualCommitAuthorEmail
- ghprbPullDescription
- ghprbPullId
- ghprbPullLink
- ghprbPullTitle
- ghprbSourceBranch
- ghprbTargetBranch
- sha1

**Comment by joestewart** [comment]
I might be misunderstanding but these environment variables are available:

pullRequestTitle
destinationRepositoryName
pullRequestId

**Comment by ghusse** [comment]
Great, I did not know it was the case. Where is it possible to find this list in the docs/readme?

**Comment by maxvodo** [comment]
@ghusse All variables, than pr-builder sets to build, you can view in [this source file](https://github.com/nishio-dens/bitbucket-pullrequest-builder-plugin/blob/master/src/main/java/bitbucketpullrequestbuilder/bitbucketpullrequestbuilder/BitbucketBuildTrigger.java#L165).

**Comment by ghusse** [comment]
Thanks.
