### ISSUE TITLE
'CI Skip Phrases' should take latest commit into account

### ISSUE THREAD

**Issue by sjaeckel** [nishio-dens/bitbucket-pullrequest-builder-plugin#78]
Currently 'CI Skip Phrases' only take the PR title into account.
It'd be very useful if the logic would also read the latest commit message (as done e.g. by travis) and look for a 'CI Skip Phrase' in there and decide to skip a build based on this.

**Comment by maxvodo** [comment]
@sjaeckel :+1: Nice feature.

**Comment by rogersdevops** [comment]
Really need this feature.
