### ISSUE TITLE
RepositoryOwner and RepositoryName is not working

### ISSUE THREAD

**Issue by anbreen** [nishio-dens/bitbucket-pullrequest-builder-plugin#81]
When I configure this plugin in jenkins, What should be specified for RepositoryOwner and RepositoryName. It is not working for the configuration in the picture. 
![screen shot 2016-04-12 at 12 41 33](https://cloud.githubusercontent.com/assets/6755882/14457673/6db946d0-00ac-11e6-987a-7908a95bed1f.png)

It only works when I hard code the repository name and repository owner, but then that makes the jenkins job specific to the mentioned repository, while I want to have the same jenkins job for all the repositories.

**Comment by anbreen** [comment]
Can someone guide me how can I create a single pull request jenkins jobs that is applicable for all my repositories and is able to fetch in RepositoryOwner and RepositoryName.
or is it not possible ?

**Comment by maxvodo** [comment]
Hi @anbreen
You use Jenkins macros to provide "RepositoryOwner" and "RepositoryName" values. I decide BBPullRequestBuilder doesn't evaluate these strings to values. Try using "solid" values, like above.

By example: we have BitBucket user with username `foo-bar`. User `foo-bar` has own private repository with name `home-stuff`. We activated BBBuild trigger. In this case field "RepositoryOwner" must contain value `foo-bar`, and field "RepositoryName" must contain value `home-stuff`.

Help needed @nishio-dens
About single job for all repos: Huh, build trigger BBPullRequestBuilder activated only for job with specific parameters, so I can guess - there is no way to do this (without new plugin modifications or new project\job type or smth).

**Comment by Mercynary** [comment]
Similar issue here! I updated the plugin today and since it doesn't work anymore because cloning fails. In contrast to the above issue I have the values hard coded (see pictures).  
![plugin-repo](https://cloud.githubusercontent.com/assets/218707/16957433/9a2b2aee-4ddc-11e6-9999-da01be21b51a.png)
![plugin-repoowner](https://cloud.githubusercontent.com/assets/218707/16957507/de5dc794-4ddc-11e6-883a-0a1ba1ce2327.png)
![plugin-log](https://cloud.githubusercontent.com/assets/218707/16957513/e6f26cde-4ddc-11e6-8729-3cc9f344047e.png)

**Comment by anbreen** [comment]
@Mercynary from the console output it looks like you are using an upstream project to trigger the build. When using BBpullrequest plugin in jenkins, a build is triggered automatically on jenkins job as soon as a pull request is created in bitbucket.

**Comment by TristanFAURE** [comment]
Hello documentation of the readme is not up to date. The correct variable name are :

- sourceRepositoryName
- sourceRepositoryOwner
