### ISSUE TITLE
Variable/Parameter with the pull request author

### ISSUE THREAD

**Issue by fonsecas72** [nishio-dens/bitbucket-pullrequest-builder-plugin#83]
Hi, could someone kindly tell me if we have a Pull Request Author variable that we can use just like the pull request title?

**Comment by maxvodo** [comment]
Right now nowhere. Today I made changes for this feature, so I need some time for tests (we can filter pull requests by author also). Wait for PR :) @fonsecas72

**Comment by fonsecas72** [comment]
@maxvodo thanks, I'm counting on you :)

**Comment by maxvodo** [comment]
So. @fonsecas72 can I gracefully ask to you try latest release of plugin with this feature. You can download it [here](https://github.com/maxvodo/bitbucket-pullrequest-builder-plugin/releases/tag/bitbucket-pullrequest-builder-fix-issue-83) and manual install after.

**Comment by fonsecas72** [comment]
@maxvodo it seems to be working indeed.
Thank you for your kindness!

**Comment by maxvodo** [comment]
After merge #84 to master by @nishio-dens, you can using release plugin version (from Jenkins repository).
