### ISSUE TITLE
Bitbucket Server

### ISSUE THREAD

**Issue by jeremyFreeAgent** [nishio-dens/bitbucket-pullrequest-builder-plugin#89]
Currently it is based on the bitbucket.org service and cannot connect to a Bitbucket server API since the endpoint and the domain are differents.

It would be great to have an option to add a Bitbucket server endpoint url to override the hardcoded endpoint.

More info here: https://developer.atlassian.com/bitbucket/server/docs/latest/how-tos/command-line-rest.html

**Comment by nickbroon** [comment]
https://github.com/nemccarthy/stash-pullrequest-builder-plugin is the server version.
Bitbucket server used to be called Stash, but this plugin should work with both.

**Comment by jeremyFreeAgent** [comment]
Thanks!

**Comment by aamol** [comment]
HI @jeremyFreeAgent ,

I am looking for the same thing which you developed. I see you have deleted your fork. If you have the code can you please share so that I dont have to do the work again :)

Thanks,
Amol
