### ISSUE TITLE
pull-request build doesn't get triggered

### ISSUE THREAD

**Issue by houmie** [nishio-dens/bitbucket-pullrequest-builder-plugin#91]
Hi all,

I really appreciate the effort behind this plugin.  I was just wondering why the pull-request builder doesn't get triggered without CRON settings.  I thought by ticking the button "Build when a change is pushed to BitBucket" would be enough for this to be triggered. But nothing happens.

And if I put \* \* \* \* \* into the CRON, it keeps building endlessly.   Any solution for this please?
Thanks

<img width="939" alt="screen shot 2016-06-07 at 15 09 04" src="https://cloud.githubusercontent.com/assets/1832933/15863487/1aaac50e-2ccb-11e6-965f-4f92ab1a2bef.png">

**Comment by dPeS** [comment]
+1

**Comment by jordanpagewhite** [comment]
+1

**Comment by kfuksmandc** [comment]
+1

**Comment by humansky** [comment]
Would it be best if the Bitbucket's webhooks trigger the build instead of relying on cron?

**Comment by unabl4** [comment]
+1. Is there a good reason NOT to use Bitbucket POST webhooks?

**Comment by frodeaa** [comment]
probably not, but I suspect cron was used because of https://bitbucket.org/site/master/issues/8340/pull-request-post-hook-does-not-include
