### ISSUE TITLE
SSH support

### ISSUE THREAD

**Issue by jmcgill-public** [nishio-dens/bitbucket-pullrequest-builder-plugin#99]
The plugin appears to support only basic auth/https. Can it support SSH?

**Comment by damovsky** [comment]
@jmcgill-public why should this plugin support ssh? do you have your bitbucket in some network which is not reachable directly ?   then why you do not make a ssh tunnel for your jenkins?

how your jenkins can read the sources from bitbucket then?

frankly, don't understand the scenario. Please, help.

**Comment by rafilkmp3** [comment]
@damovsky my scenario is , i wish provide only a deploy key to jenkins use, and i have another problem, my bitibucket uses google Oauth so i really cant provide this in basicAuth form.

**Comment by vle-tom** [comment]
I'd like to second this request. I would like to use the ssh authentication method so that I do not have to supply a username/password.

**Comment by povils** [comment]
I also agree

**Comment by fromi** [comment]
I also need this feature : I want to secure my Bitbucket account with a two-factor authentication, but it prevents this plugin to work.

**Comment by ip1981** [comment]
> my bitibucket uses google Oauth so i really cant provide this in basicAuth form.

This does not make sense. This plugin uses Bitbucket API with Basic Auth. It does not use Git/SSH

You have to configure "App passwords"  in your profile (Setting -> Access Management).

**Comment by ip1981** [comment]
> App passwords allow two-step verification users to access their Bitbucket account through apps such as Sourcetree. We'll generate the app passwords for you, and you won't need to remember them.

**Comment by ip1981** [comment]
> I'd like to second this request. I would like to use the ssh authentication method so that I do not have to supply a username/password.

This plugin uses Bitbucket RESTful API, not Git ove https or ssh or git..
